# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: webcam.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'webcam.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwebcam.proto\x12\x06webcam\"\x1e\n\rStreamRequest\x12\r\n\x05start\x18\x01 \x01(\x08\"\x15\n\x05\x46rame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"7\n\x0c\x46ocusRequest\x12\x12\n\nauto_focus\x18\x01 \x01(\x08\x12\x13\n\x0b\x66ocus_value\x18\x02 \x01(\x05\"1\n\rFocusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x7f\n\rWebCamService\x12\x35\n\x0bStreamVideo\x12\x15.webcam.StreamRequest\x1a\r.webcam.Frame0\x01\x12\x37\n\x08SetFocus\x12\x14.webcam.FocusRequest\x1a\x15.webcam.FocusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'webcam_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=24
  _globals['_STREAMREQUEST']._serialized_end=54
  _globals['_FRAME']._serialized_start=56
  _globals['_FRAME']._serialized_end=77
  _globals['_FOCUSREQUEST']._serialized_start=79
  _globals['_FOCUSREQUEST']._serialized_end=134
  _globals['_FOCUSRESPONSE']._serialized_start=136
  _globals['_FOCUSRESPONSE']._serialized_end=185
  _globals['_WEBCAMSERVICE']._serialized_start=187
  _globals['_WEBCAMSERVICE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
