# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import webcam_pb2 as webcam__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in webcam_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WebCamServiceStub(object):
    """定義 WebCam 串流服務
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVideo = channel.unary_stream(
                '/webcam.WebCamService/StreamVideo',
                request_serializer=webcam__pb2.StreamRequest.SerializeToString,
                response_deserializer=webcam__pb2.Frame.FromString,
                _registered_method=True)
        self.SetFocus = channel.unary_unary(
                '/webcam.WebCamService/SetFocus',
                request_serializer=webcam__pb2.FocusRequest.SerializeToString,
                response_deserializer=webcam__pb2.FocusResponse.FromString,
                _registered_method=True)


class WebCamServiceServicer(object):
    """定義 WebCam 串流服務
    """

    def StreamVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFocus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebCamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamVideo,
                    request_deserializer=webcam__pb2.StreamRequest.FromString,
                    response_serializer=webcam__pb2.Frame.SerializeToString,
            ),
            'SetFocus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFocus,
                    request_deserializer=webcam__pb2.FocusRequest.FromString,
                    response_serializer=webcam__pb2.FocusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'webcam.WebCamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('webcam.WebCamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WebCamService(object):
    """定義 WebCam 串流服務
    """

    @staticmethod
    def StreamVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/webcam.WebCamService/StreamVideo',
            webcam__pb2.StreamRequest.SerializeToString,
            webcam__pb2.Frame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFocus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/webcam.WebCamService/SetFocus',
            webcam__pb2.FocusRequest.SerializeToString,
            webcam__pb2.FocusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
