# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\ngeminichat\"\x9c\x01\n\x0b\x43hatMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x03 \x01(\t\x12/\n\rline_metadata\x18\x04 \x01(\x0b\x32\x18.geminichat.LineMetadata\x12\x12\n\nimage_data\x18\x05 \x01(\x0c\x12\x17\n\x0fimage_mime_type\x18\x06 \x01(\t\"a\n\x0cLineMetadata\x12\x13\n\x0breply_token\x18\x01 \x01(\t\x12\x14\n\x0cmessage_type\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\x12\n\nsticker_id\x18\x04 \x01(\t\"\x19\n\tChatReply\x12\x0c\n\x04text\x18\x01 \x01(\t2N\n\x0b\x43hatService\x12?\n\x0bSendMessage\x12\x17.geminichat.ChatMessage\x1a\x15.geminichat.ChatReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=27
  _globals['_CHATMESSAGE']._serialized_end=183
  _globals['_LINEMETADATA']._serialized_start=185
  _globals['_LINEMETADATA']._serialized_end=282
  _globals['_CHATREPLY']._serialized_start=284
  _globals['_CHATREPLY']._serialized_end=309
  _globals['_CHATSERVICE']._serialized_start=311
  _globals['_CHATSERVICE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
